[package]
name = "notetaker"
version = "0.1.0"
authors = ["SmallPlayz <900raiyan@gmail.com>"]
edition = "2021"
build = "build.rs"

[dependencies]
slint = "1.4"
nfd = "0.0.4"

[build-dependencies]
slint-build = "1.4"

[package.metadata.winres]
features = ["windows-subsystem"]
