import { Button, VerticalBox, GridBox, LineEdit, TextEdit, HorizontalBox } from "std-widgets.slint";

export component AppWindow inherits Window {

    callback open-note();
    callback save-note();
    callback new-note();

    GridBox {
        padding: 16px;
        spacing: 10px;
        Row {
            HorizontalBox {
                Button {
                    text: "Open";
                    clicked => {open-note()}
                }
                Button {
                    text: "Save";
                    clicked => {save-note()}
                }
                Button {
                    text: "New";
                    clicked => {new-note()}
                }
            }
        }

        Row {
            title := LineEdit {
                placeholder-text: "Title goes here";
                horizontal-alignment: center;
            }
        }

        Row {
            currentNote := TextEdit {
                height: 50px;
            }
        }
    }
}
