import { Button, VerticalBox, GridBox, LineEdit, TextEdit, HorizontalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    title: "NoteTaker";
    icon: @image-url("icon.png");

    in property <string> file-title;
    in property <string> file-contents;

    callback open-note();
    callback save-note(string, string);
    callback new-note();

    GridBox {
        padding: 16px;
        spacing: 10px;
        Row {
            HorizontalBox {
                Button {
                    text: "Open";
                    clicked => {open-note()}
                }
                Button {
                    text: "Save";
                    clicked => {save-note(title.text, currentNote.text)}
                }
                Button {
                    text: "New";
                    clicked => {new-note()}
                }
            }
        }

        Row {
            title := LineEdit {
                vertical-stretch: 0;
                placeholder-text: "Title goes here";
                horizontal-alignment: center;
                text: root.file-title;
            }
        }

        Row {
            currentNote := TextEdit {
                min-height: 50px;
                text: root.file-contents;
            }
        }
    }
}
